import type { NextPage } from "next";
import Head from "next/head";
import PokemonSearch from "../components/templates/pokemon-search";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon Search Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Pokemon Search Demo</h1>
        <p>Using NextJS, context, stitches, and Radix UI</p>
        <PokemonSearch />
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/kaplantm" target="_blank" rel="noopener noreferrer">
          Github
        </a>
      </footer>
    </div>
  );
};

export default Home;
