import type { NextPage } from "next";
import Head from "next/head";
import StyledDiv from "../components/atoms/StyledDiv";
import PokemonSearch from "../components/templates/pokemon-search";

const Home: NextPage = () => {
  return (
    <StyledDiv css={{ padding: "2rem" }}>
      <Head>
        <title>Pokemon Search Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Pokemon Search Demo</h1>
        <p>Using NextJS, context, stitches, and Radix UI</p>

        <PokemonSearch />
      </main>

      <footer>
        <a href="https://github.com/kaplantm" target="_blank" rel="noopener noreferrer">
          Github
        </a>
      </footer>
    </StyledDiv>
  );
};

export default Home;
